---
title: "git_00"
author: "Alfredo Acevedo"
date: "Year 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
She took her little porringer:  
Of me she shall not win renown:  
For the baseness of its nature shall have strength to drag her  
down. 
"Sisters and brothers, little Maid?   
There stands the Inspector at thy door  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
   
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Let the last touch of your hands be  
gentle like the flower of the night.  
Stand still, O Beautiful End, for a  
moment, and say your last words in  
silence.  
I bow to you and hold up my lamp  
to light you on your way.  
I try and cope the best I can  
But I’m missing you so much  
If I could only see you  
And once more feel your touch.  
Yes, you’ve just walked on ahead of me  
Don’t worry I’ll be fine  
But now and then I swear I feel  
Your hand slip into mine.  
  